import StatusCell from "@/components/CustomTable/_comps/StatusCell";

export const STATUSOPTIONS = {
  trades: [
    { value: "LISTED", display: "LISTED" },
    { value: "QUEUED", display: "QUEUED" },
    { value: "COMPLETE", display: "COMPLETE" },
    { value: "CANCELLED", display: "CANCELLED" },
    { value: "LISTING REMOVED", display: "LISTING REMOVED" },
    { value: "PROCESSING", display: "PROCESSING" },
  ],
};

export const columns = [
  {
    id: "windowId",
    accessorKey: "_id",
    header: "Window ID",
  },
  {
    id: "listingId",
    accessorKey: "listingId",
    header: "Listing ID",
  },
  {
    id: "noOfSharesListing",
    accessorKey: "noOfSharesListing",
    header: "No. of Shares Listing",
  },
  {
    id: "shareValue",
    accessorKey: "shareValue",
    header: "Share Value",
  },
  {
    id: "listedSharePrice",
    accessorKey: "listedSharePrice",
    header: "Listed Share Price",
  },
  {
    id: "trades",
    type: "select",
    accessorKey: "status",
    header: "Status",
    cell: StatusCell,
  },

  {
    id: "investorId",
    accessorKey: "investorId",
    header: "Investor ID (Buyer)",
  },
  {
    id: "campaignId",
    accessorKey: "campaignId",
    header: "Campaign ID",
  },
  {
    id: "propertyId",
    accessorKey: "propertyId",
    header: "Property ID",
  },
  {
    id: "campaignCreationTimestamp",
    type: "date",
    accessorKey: "createdAt",
    header: "Created on",
  },
  {
    accessorKey: "updatedAt",
    type: "date",
    header: "Last Updated",
  },
  {
    id: "updatedBy",
    accessorKey: "updatedBy",
    header: "Updated by",
  },
];

export const data = [
  {
    _id: "aCXM-1",
    listingId: "dAhmed",
    noOfSharesListing: "test@example.com",
    shareValue: "+79053752552",
    listedSharePrice: "LIVE",
    status: "LISTED",
    investorId: "test@example.com",
    campaignId: "",
    propertyId: "",
    createdAt: "11:22:32 | 20/12/2023",
    updatedAt: "11:22:32 | 20/12/2023",
    updatedBy: "CXM-4",
  },
  {
    _id: "aCXM-1",
    listingId: "dAhmed",
    noOfSharesListing: "test@example.com",
    shareValue: "+79053752552",
    listedSharePrice: "QUEUED",
    status: "QUEUED",
    investorId: "test@example.com",
    campaignId: "",
    propertyId: "",
    createdAt: "11:22:32 | 20/12/2023",
    updatedAt: "11:22:32 | 20/12/2023",
    updatedBy: "CXM-4",
  },
  {
    _id: "aCXM-1",
    listingId: "dAhmed",
    noOfSharesListing: "test@example.com",
    shareValue: "+79053752552",
    listedSharePrice: "LIVE",
    status: "COMPLETE",
    investorId: "test@example.com",
    campaignId: "",
    propertyId: "",
    createdAt: "11:22:32 | 20/12/2023",
    updatedAt: "11:22:32 | 20/12/2023",
    updatedBy: "CXM-4",
  },
  {
    _id: "aCXM-1",
    listingId: "dAhmed",
    noOfSharesListing: "test@example.com",
    shareValue: "+79053752552",
    listedSharePrice: "LIVE",
    status: "CANCELLED",
    investorId: "test@example.com",
    campaignId: "",
    propertyId: "",
    createdAt: "11:22:32 | 20/12/2023",
    updatedAt: "11:22:32 | 20/12/2023",
    updatedBy: "CXM-4",
  },
  {
    _id: "aCXM-1",
    listingId: "dAhmed",
    noOfSharesListing: "test@example.com",
    shareValue: "+79053752552",
    listedSharePrice: "LIVE",
    status: "LISTING_REMOVED",
    investorId: "test@example.com",
    campaignId: "",
    propertyId: "",
    createdAt: "11:22:32 | 20/12/2023",
    updatedAt: "11:22:32 | 20/12/2023",
    updatedBy: "CXM-4",
  },
  {
    _id: "aCXM-1",
    listingId: "dAhmed",
    noOfSharesListing: "test@example.com",
    shareValue: "+79053752552",
    listedSharePrice: "LIVE",
    status: "PROCESSING",
    investorId: "test@example.com",
    campaignId: "",
    propertyId: "",
    createdAt: "11:22:32 | 20/12/2023",
    updatedAt: "11:22:32 | 20/12/2023",
    updatedBy: "CXM-4",
  },
];
