import {
  List,
  CaretRight,
  CaretLeft,
  ProjectorScreenChart,
  MapPinLine,
  BellRinging,
  CaretCircleLeft,
  CaretCircleRight,
  CaretDown,
  CaretUp,
  Check,
  DotsNine,
  X,
  ArrowRight,
  ChartLineUp,
  ArrowLeft,
  Plus,
  Minus,
  CornersOut,
  ArrowsCounterClockwise,
  DownloadSimple,
  UploadSimple,
  Eye,
  PencilSimple,
  Trash,
  Info,
  CalendarBlank,
  MagnifyingGlass,
  SignOut,  
  ImageSquare,
  WarningCircle,
  CheckCircle,
  Circle,
  Lock,
  MapPin,
  DotsThreeVertical,
  CopySimple,
  Copy,
  XCircle
} from "@phosphor-icons/react/dist/ssr";

import CampaignsIcon from "./CampaignsIcon";
import NotificaionsIcon from "./NotificaionsIcon";
import SupportIcon from "./SupportIcon";
import TeamIcon from "./TeamIcon";



export {
  List,
  CaretRight,
  CaretLeft,
  CaretCircleLeft,
  CaretCircleRight,
  CaretDown,
  CaretUp,
  Check,
  DotsNine,
  X,
  ArrowRight,
  ChartLineUp,
  ArrowLeft,
  Plus,
  Minus,
  CornersOut,
  ArrowsCounterClockwise,
  DownloadSimple,
  UploadSimple,
  Eye,
  PencilSimple,
  Trash,
  Info,
  CalendarBlank,
  MagnifyingGlass,
  CampaignsIcon,
  BellRinging,
  MapPinLine,
  ProjectorScreenChart,
  SupportIcon,
  NotificaionsIcon,
  TeamIcon,
  SignOut,
  ImageSquare,
  WarningCircle,
  CheckCircle,
  Circle,
  Lock,
  MapPin,
  DotsThreeVertical,
  CopySimple,
  Copy,
  XCircle
};
