export enum SORTYBY {
  campaignId = "campaignId",
  assetName = "assetName",
  sellerId = "sellerId",
  propertyPrice = "propertyPrice",
  sharePrice = "sharePrice",
  campaignCreationTimestamp = "campaignCreationTimestamp",
  campaignPublishingTimestamp = "campaignPublishingTimestamp",
  campaignCloseTimestamp = "campaignCloseTimestamp",
  campaignStatus = "campaignStatus",
}

export enum SORTORDER {
  ASC = "ASC",
  DESC = "DESC",
}

export enum STATUS {
  UNPUBLISHED = "UNPUBLISHED",
  PUBLISHED = "PUBLISHED",
  PENDING = "PENDING",
  PENDING_FEE = "PENDING FEE",
  PENDING_REVIEW = "PENDING_REVIEW",
  DRAFT = "DRAFT",
  ACTIVE = "ACTIVE",
  SCHEDULED = "SCHEDULED",
  REJECTED = "REJECTED",
  APPROVED_TO_PUBLISH = "APPROVED TO PUBLISH",
  INCOMPLETE = "INCOMPLETE",
  COMPLETE = "COMPLETE",
  LIVE = "LIVE",
  CLOSED = "CLOSED",
  LISTED = "LISTED",
  QUEUED = "QUEUED",
  CANCELLED = "CANCELLED",
  LISTING_REMOVED = "LISTING_REMOVED",
  PROCESSING = "PROCESSING",
  FAILED = "FAILED",
  APPROVED = "APPROVED",
  EXPIRED = "EXPIRED",
  INVITED = "INVITED",
  BLOCKED = "BLOCKED",
  REGISTERED = "REGISTERED",
  UNDER_REVIEW = "UNDER_REVIEW",
  VERIFIED = "VERIFIED",
  ACTION_REQUIRED = "ACTION_REQUIRED",
  BUSINESS = "BUSINESS",
  ACCEPTED = "ACCEPTED",
  AVAILABLE = "AVAILABLE",
  UNLISTED = "UNLISTED",
}
