
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../style/globals.css";
import Provider from "@/providers/provider";
import Sidebar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CX Seller",
  description: "Generated by create next app",
};

export default async function RootLayout({children}: {children: React.ReactNode}) {

  return (   
     <html lang="en"> {/*TODO: set thw lang dynamically*/}
     <body className={`w-full flex md:flex-row flex-col ${inter.className}`}>
       <Provider>
          <Sidebar />
           <main className="w-full">{children}</main>
       </Provider>
     </body>
   </html>
  );
}
