import type { Metadata } from "next";

import "@/../styles/globals.css";
import Provider from "@/providers/provider";
import Sidebar from "@/components/Sidebar";
import Loading from "@/app/[locale]/loading";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "CX Media",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <html lang={locale}>
      <body className=" w-full flex md:flex-row flex-col bg-[#FFFAF8]">
        <Provider locale={locale}>
          <Sidebar />
          <Suspense fallback={<Loading />}>
            <main className="w-full flex h-screen relative">{children}</main>
          </Suspense>
        </Provider>
      </body>
    </html>
  );
}
